CREATE USER IF NOT EXISTS 'flink'@'%' IDENTIFIED WITH mysql_native_password BY 'flink_pw';
GRANT SELECT, RELOAD, SHOW DATABASES, REPLICATION SLAVE, REPLICATION CLIENT ON *.* TO 'flink'@'%';
FLUSH PRIVILEGES;
